@baseURL = http://localhost:3000/auth
@content
@contentType = application/json
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbmlzLmt1bGlrb3ZAZXJnLmt6IiwiaWF0IjoxNjQ1Nzc4MDExLCJleHAiOjE2NDU3ODE2MTF9.MwEY7BeQslI3AeURYjwRFxNg375Ck8MEKP8xtClCjgg

### LIST ALL USERS
GET {{baseURL}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

### GET USER BY ID
GET {{baseURL}}/2 HTTP/1.1
Content-Type: {{contentType}}

### REGISTER
POST {{baseURL}}/register HTTP/1.1
Content-Type: {{contentType}}

{
  "email" : "denis.kulikov@erg.kz",
  "password" : "Miranda32"
}

### LOGIN 
POST {{baseURL}}/login HTTP/1.1
Content-Type: {{contentType}}

{
  "email" : "denis.kulikov@erg.kz",
  "password" : "Miranda32"
}


### UPDATE USER
PATCH {{baseURL}}/3 HTTP/1.1
Content-Type: {{contentType}}

{
  "email" : "nottest@gmail.com"  
}

### DELETE USER
DELETE {{baseURL}}/3 HTTP/1.1
Content-Type: {{contentType}}