@baseURL = https://3000-solarpath-kenobi-ebxewjfaq8b.ws-eu31.gitpod.io/todos
@content
@contentType = application/json

### LIST ALL TODOS
GET {{baseURL}}/todo HTTP/1.1
Content-Type: {{contentType}}

### GET COMPANY BY ID
GET {{baseURL}}/todo/2 HTTP/1.1
Content-Type: {{contentType}}

### CREATE A COMPANY
POST {{baseURL}}/todo HTTP/1.1
Content-Type: {{contentType}}

{
  "title" : "fourth",       
  "description" : "lorum ipsum dolorum"
}

### UPDATE COMPANY
PATCH {{baseURL}}/todo/4 HTTP/1.1
Content-Type: {{contentType}}

{
  "title" : "fourth"  
}

### DELETE COMPANY
DELETE {{baseURL}}/todo/5 HTTP/1.1
Content-Type: {{contentType}}